- name: Install firewalld.
  hosts: all
  remote_user: root 
  tasks: 
    - name: Update  
      apt:
        update_cache: yes
    - name: Install firewalld.
      apt:
        name: firewalld
        state: present