- name: Install and configure Grafana.
  hosts: all
  remote_user: root 
  tasks: 
    - name: Update  
      apt:
        update_cache: yes
    - name: Install grafana installation dependency "adduser".
      apt:
        name: adduser
        state: present
    - name: Install grafana installation dependency "libfontconfig1".
      apt:
        name: libfontconfig1
        state: present
    - name: Download grafana deb file.
      get_url: 
        url: https://dl.grafana.com/oss/release/grafana_6.6.1_amd64.deb
        dest: ~/
    - name: Install grafana from deb file.
      apt:
        deb: ~/grafana_6.6.1_amd64.deb
    - name: enable service grafana and ensure it is not masked
      systemd:
        name: grafana-server
        enabled: yes
        masked: no
    - name: Make sure service is running
      systemd:
        state: started
        name: grafana-server
    - name: Display Grafana server adress.
      debug:
        msg: Grafana can be accessed at http://{{ ansible_default_ipv4.address }}:3000