- name: Install and configure Elasticsearch
  hosts: all
  remote_user: root 
  tasks: 
    - name: Update  
      apt:
        update_cache: yes
    - name: Install elasticsearch installation requirement
      apt:
        name: apt-transport-https
        state: present
    - name: Add an Apt signing key, uses whichever key is at the URL
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        state: present
    - name: Add specified repository into sources list using specified filename.
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/7.x/apt stable main
        state: present
        filename: elastic-7.x
    - name: Update  
      apt:
        update_cache: yes
    - name: Install elasticsearch
      apt:
        name: elasticsearch
        state: present
    - name: replace line in configuration file -> Set minimal java memory to 256m
      lineinfile: 
        dest: /etc/elasticsearch/jvm.options
        regexp: '^(.*)## -Xms4g(.*)$' 
        line: '-Xms256m'
        backrefs: yes
    - name: replace line in configuration file -> Set maximal java memory to 256m
      lineinfile: 
        dest: /etc/elasticsearch/jvm.options
        regexp: '^(.*)## -Xmx4g(.*)$' 
        line: '-Xmx256m'
        backrefs: yes
    - name: Reload systemd dameon
      systemd:
        daemon_reload: yes
    - name: enable service elasticsearch and ensure it is not masked
      systemd:
        name: elasticsearch.service
        enabled: yes
        masked: no
    - name: stop service elasticsearch
      systemd:
        state: stopped
        name: elasticsearch
    - name: start service elasticsearch
      systemd:
        state: started
        name: elasticsearch
    - name: Make sure service elasticsearch is running
      systemd:
        state: started
        name: elasticsearch